package mil.disa.oe.repository;

import mil.disa.oe.config.TableNames;
import mil.disa.oe.dto.*;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.retry.annotation.Backoff;
import org.springframework.retry.annotation.Retryable;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collections;
import java.util.List;

/** Source: NETCOOL (Network Event Management & Alerting) */
@Repository
public class TopIssuesRepository {

    private final NamedParameterJdbcTemplate jdbc;
    private final TableNames tables;

    public TopIssuesRepository(NamedParameterJdbcTemplate jdbc, TableNames tables) {
        this.jdbc   = jdbc;
        this.tables = tables;
    }

    // ── Hive JDBC compatibility ───────────────────────────────────────────
    // Hive JDBC 3.1.x returns DOUBLE columns as java.lang.Double, not BigDecimal.
    // Databricks JDBC returns BigDecimal. These helpers normalise both drivers.

    private static BigDecimal bd(ResultSet rs, String col) throws SQLException {
        double v = rs.getDouble(col);
        return rs.wasNull() ? null : BigDecimal.valueOf(v);
    }

    private static BigDecimal bd(Object val) {
        if (val == null) return null;
        if (val instanceof BigDecimal b) return b;
        return BigDecimal.valueOf(((Number) val).doubleValue());
    }

    @Retryable(retryFor = Exception.class, maxAttempts = 3,
               backoff = @Backoff(delay = 2000, multiplier = 2.0))
    public IssuesKpis getKpis() {
        String kpiSql = """
            SELECT
                COUNT(CASE WHEN severity='P1' AND status!='RESOLVED' THEN 1 END) AS p1_open,
                COUNT(CASE WHEN severity='P2' AND status!='RESOLVED' THEN 1 END) AS p2_open,
                COUNT(CASE WHEN severity='P3' AND status!='RESOLVED' THEN 1 END) AS p3_open,
                COUNT(CASE WHEN severity='P4' AND status!='RESOLVED' THEN 1 END) AS p4_open,
                COUNT(CASE WHEN status != 'RESOLVED'                 THEN 1 END) AS total_open,
                COUNT(CASE WHEN status = 'RESOLVED'
                            AND DATE(resolved_at) = current_date()   THEN 1 END) AS resolved_today,
                ROUND(AVG(CASE WHEN status='RESOLVED'
                          THEN mttr_minutes END) / 60.0, 1)                      AS avg_mttr_hours,
                ROUND(COUNT(CASE WHEN sla_breached = true THEN 1 END)
                      * 100.0 / NULLIF(COUNT(*),0), 1)                           AS sla_breach_rate
            FROM %s
            WHERE opened_at >= current_date() - 30
            """.formatted(tables.topIssuesSummary());

        String byCatSql = """
            SELECT category,
                   COUNT(CASE WHEN status != 'RESOLVED' THEN 1 END) AS open_count,
                   COUNT(CASE WHEN status = 'RESOLVED'  THEN 1 END) AS resolved_count,
                   ROUND(AVG(CASE WHEN status='RESOLVED'
                             THEN mttr_minutes END) / 60.0, 1)       AS avg_mttr
            FROM %s
            WHERE opened_at >= current_date() - 30
            GROUP BY category
            ORDER BY open_count DESC
            """.formatted(tables.topIssuesSummary());

        // ── Trending Issues ───────────────────────────────────────────────
        // The original query used gold.issue_trends which is a separate table
        // not generated by the current pipeline (NETCOOL → top_issues_summary only).
        //
        // On AWS GovCloud with Databricks, issue_trends would be populated by
        // a dedicated ML/pattern-detection job. For local dev we derive a
        // proxy trending view from top_issues_summary: most recurring issues
        // by category serve as a stand-in for pattern analysis.
        //
        // To restore the original: replace this query with the issueTrends()
        // table reference once the trend aggregation job is implemented.
        String trendingSql = """
            SELECT category                               AS pattern,
                   COUNT(*)                               AS occurrences,
                   category                               AS affected_component,
                   CASE WHEN COUNT(*) > 50 THEN 'INCREASING'
                        WHEN COUNT(*) > 20 THEN 'STABLE'
                        ELSE 'DECREASING'
                   END                                    AS trend
            FROM %s
            WHERE opened_at >= current_date() - 30
              AND is_recurring = true
            GROUP BY category
            ORDER BY occurrences DESC
            LIMIT 5
            """.formatted(tables.topIssuesSummary());

        String criticalSql = """
            SELECT issue_id, title, category, severity, status, source,
                   affected_devices, affected_users, opened_at, last_updated_at,
                   resolved_at, mttr_minutes, assigned_team, root_cause,
                   is_recurring, occurrence_count
            FROM %s
            WHERE severity IN ('P1','P2')
              AND status != 'RESOLVED'
            ORDER BY severity, opened_at ASC
            LIMIT 10
            """.formatted(tables.topIssuesSummary());

        var r = jdbc.queryForMap(kpiSql, Collections.emptyMap());

        List<IssuesByCategory> byCat = jdbc.query(byCatSql,
            Collections.emptyMap(), (rs, i) -> new IssuesByCategory(
                rs.getString("category"), rs.getInt("open_count"),
                rs.getInt("resolved_count"), bd(rs, "avg_mttr")));

        List<TrendingIssue> trending = jdbc.query(trendingSql,
            Collections.emptyMap(), (rs, i) -> new TrendingIssue(
                rs.getString("pattern"), rs.getInt("occurrences"),
                rs.getString("affected_component"), rs.getString("trend")));

        List<TopIssueSummary> critical = jdbc.query(criticalSql,
            Collections.emptyMap(), (rs, i) -> new TopIssueSummary(
                rs.getString("issue_id"), rs.getString("title"),
                rs.getString("category"), rs.getString("severity"),
                rs.getString("status"), rs.getString("source"),
                rs.getInt("affected_devices"), rs.getInt("affected_users"),
                rs.getTimestamp("opened_at").toLocalDateTime(),
                rs.getTimestamp("last_updated_at").toLocalDateTime(),
                rs.getTimestamp("resolved_at") != null
                    ? rs.getTimestamp("resolved_at").toLocalDateTime() : null,
                rs.getLong("mttr_minutes"), rs.getString("assigned_team"),
                rs.getString("root_cause"), rs.getBoolean("is_recurring"),
                rs.getInt("occurrence_count")));

        return new IssuesKpis(
            ((Number) r.get("p1_open")).intValue(),
            ((Number) r.get("p2_open")).intValue(),
            ((Number) r.get("p3_open")).intValue(),
            ((Number) r.get("p4_open")).intValue(),
            ((Number) r.get("total_open")).intValue(),
            ((Number) r.get("resolved_today")).intValue(),
            bd(r.get("avg_mttr_hours")),
            bd(r.get("sla_breach_rate")),
            byCat, trending, critical);
    }
}